### ISSUE TITLE
Bug: Command executed by console doesn't have warmup time

### ISSUE THREAD

**Issue by NoltoxGit** [WiIIiam278/HuskHomes#630]
Hello,
When I use the `huskhomes:warp WARP_NAME %player_name%` in the console, the player doesn't have the cooldown specified in the config (`teleport_warmup_time: 3`)

**Comment by WiIIiam278** [comment]
This is working as intended. Teleport operations only use warmup if the action is self-initiated. Otherwise, the user does not expect to be placed into a teleport warmup and will be confused / annoyed when their teleport is instantly cancelled because they were moving when it was initiated.

If you are making some sort of GUI thing to teleport users via console when they request it, you should have the player self-execute the warp command as a result of using your menu to initiate the standard teleport procedure. If your needs are more complex, consider using the API.
